version: "3.9"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: admin12345
      MYSQL_DATABASE: inventory
      MYSQL_USER: root
      DB_HOST: db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin12345
      MYSQL_DATABASE: inventory
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/mysql