version: "3.9"
services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: inventory
    ports:
      - "3307:3306"
    tty: true

  web:
    build: .
    command: bash -c "bash ./init.sh && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db:mysql
    links:
      - db
    environment:
      - DB_USER=root
      - DB_NAME=inventory
      - DB_HOST=db

volumes:
  db:
