default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DB_NAME'] %>
  # username: <%= ENV['DB_USER'] %>
  username: root
  password: admin12345
  socket: /tmp/mysql.sock
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: <%= ENV['DEV_DB_DATABASE'] %>
  username: <%= ENV['DEV_DB_USERNAME'] %>
  password: <%= ENV['DEV_DB_PASSWORD'] %>

test:
  <<: *default
  adapter: mysql2
  database: <%= ENV['TEST_DB_DATABASE']%>
  username: <%= ENV['TEST_DB_USERNAME']%>
  password: <%= ENV['TEST_DB_PASSWORD ']%>
  host: localhost

production:
  <<: *default
  database: inventory_api_production
  username: root
  password: <%= ENV['INVENTORY_API_DATABASE_PASSWORD'] %>

staging:
  <<: *default
  database: <%= ENV['STAGING_DB_DATABASE']%>
  username: <%= ENV['STAGING_DB_USERNAME']%>
  password: <%= ENV['STAGING_DB_PASSWORD']%>
  secret_key_base: <%= ENV['SECRET_KEY_BASE']%>
  host: localhost
