default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: 'admin12345'
  host: db

development:
  <<: *default
  database: inventory

test:
  <<: *default
  database: inventory

production:
  <<: *default
  database: inventory_api_production
  username: root
  password: <%= ENV['INVENTORY_API_DATABASE_PASSWORD'] %>
